name: studie
description: An E-Learning app which helps students to connect with friends, teachers easily and provides useful functions for efficient, productive learning.

publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.5
  percent_indicator: ^4.2.2
  flutter_riverpod: ^2.1.3
  permission_handler: ^10.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.2
  syncfusion_flutter_pdfviewer: ^20.3.49
  agora_rtc_engine: ^6.1.0
  lottie: ^2.2.0
  file_picker: ^5.2.2
  firebase_storage: ^11.0.10
  photo_view: ^0.14.0
  just_audio: ^0.9.30
  http: ^0.13.5
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Regular.ttf
